import { Client } from '@/types/clients';

export const mockClients: Client[] = [
    {
        id: '1',
        firstName: 'Alex',
        lastName: 'Thompson',
        email: 'alex.thompson@email.com',
        phone: '+1 555-1001',
        membershipId: '2',
        membershipName: 'Premium Membership',
        assignedStaffId: '1',
        assignedStaffName: 'Sarah Johnson',
        status: 'active',
        joinDate: '2023-06-15',
        lastVisit: '2024-01-30',
    },
    {
        id: '2',
        firstName: 'Jordan',
        lastName: 'Lee',
        email: 'jordan.lee@email.com',
        phone: '+1 555-1002',
        membershipId: '1',
        membershipName: 'Basic Membership',
        assignedStaffId: '8',
        assignedStaffName: 'Robert Martinez',
        status: 'active',
        joinDate: '2023-08-20',
        lastVisit: '2024-01-29',
    },
    {
        id: '3',
        firstName: 'Taylor',
        lastName: 'Morgan',
        email: 'taylor.morgan@email.com',
        phone: '+1 555-1003',
        membershipId: '3',
        membershipName: 'Annual Elite',
        assignedStaffId: '1',
        assignedStaffName: 'Sarah Johnson',
        status: 'active',
        joinDate: '2023-01-10',
        lastVisit: '2024-01-30',
    },
    {
        id: '4',
        firstName: 'Casey',
        lastName: 'Wilson',
        email: 'casey.wilson@email.com',
        phone: '+1 555-1004',
        membershipId: '4',
        membershipName: '10-Class Pack',
        status: 'active',
        joinDate: '2023-11-05',
        lastVisit: '2024-01-25',
    },
    {
        id: '5',
        firstName: 'Drew',
        lastName: 'Anderson',
        email: 'drew.anderson@email.com',
        phone: '+1 555-1005',
        membershipId: '2',
        membershipName: 'Premium Membership',
        assignedStaffId: '2',
        assignedStaffName: 'Michael Chen',
        status: 'active',
        joinDate: '2023-09-12',
        lastVisit: '2024-01-28',
    },
    {
        id: '6',
        firstName: 'Riley',
        lastName: 'Garcia',
        email: 'riley.garcia@email.com',
        status: 'pending',
        joinDate: '2024-01-28',
    },
    {
        id: '7',
        firstName: 'Quinn',
        lastName: 'Martinez',
        email: 'quinn.martinez@email.com',
        phone: '+1 555-1007',
        membershipId: '1',
        membershipName: 'Basic Membership',
        status: 'inactive',
        joinDate: '2023-03-20',
        lastVisit: '2023-10-15',
    },
    {
        id: '8',
        firstName: 'Avery',
        lastName: 'Robinson',
        email: 'avery.robinson@email.com',
        phone: '+1 555-1008',
        membershipId: '5',
        membershipName: '25-Class Pack',
        assignedStaffId: '8',
        assignedStaffName: 'Robert Martinez',
        status: 'active',
        joinDate: '2023-10-01',
        lastVisit: '2024-01-30',
    },
];

export async function fetchClients(): Promise<Client[]> {
    await new Promise((resolve) => setTimeout(resolve, 600));
    return mockClients;
}
